name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "OSS Build"
            features: ""
          - name: "EE Build"
            features: "--features ee_feature"
    
    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Check formatting
        run: cargo fmt --check
        
      - name: Check clippy (OSS)
        if: matrix.features == ''
        run: cargo clippy -- -D warnings
        
      - name: Check clippy (EE)
        if: matrix.features != ''
        env:
          SQLX_OFFLINE: true
        run: cargo clippy ${{ matrix.features }} -- -D warnings
        
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: cargo build --verbose ${{ matrix.features }}
        
      - name: Run tests
        run: cargo test --verbose ${{ matrix.features }}
